services:
  - type: web
    name: snappycards-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: SUPABASE_URL
        value: https://ycxqxdhaxehspypqbnpi.supabase.co
      - key: SUPABASE_SERVICE_KEY
        sync: false # Set this in Render dashboard for security
      - key: RESEND_API_KEY
        sync: false # Set this in Render dashboard for security 